version: '3'

services:
  frontend:
    build:
      context: ./frontend/react-file-upload
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

networks:
  app-network:
    driver: bridge
